# Generated by Django 5.1.4 on 2025-01-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userstatus_alter_chatroom_options_chatroom_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_read_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
