# Generated by Django 5.1.4 on 2025-01-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
