# Generated by Django 5.1.4 on 2025-01-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='size',
        ),
    ]
